markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: http://saigonlug.org
help_url: http://saigonlug.org
timezone: America/Los_Angeles
